config/routes.rb
  Rails.application.routes.draw do
    devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    root 'products#index'
    resources :products do                  #products_controllerに対してのresourcesメソッド
      resources :reviews, only: [:new,:create]
    end
    resources :users, only: [:show]       #users_controllerに対してのresourcesメソッド

  end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :reviews              #reviewsテーブルとのアソシエーション

  def review_average
    reviews.average(:rate).round
  end
end

app/controllers/products_controller.rb
class ProductsController < RankingController

    before_action :move_to_index, except: :index

    def index
      @products = Product.includes(:user).page(params[:page]).per(10).order("created_at DESC")
    end

    def new
      @product = Product.new
      @review = Review.new
    end

    def create
    # @product = Product.new(product_params,user_id: current_user.id)

    # respond_to do |format|
    #   if @product.save
    #     format.html { redirect_to @product, notice: 'Post was successfully created.' }
    #     format.json { render :show, status: :created, location: @product }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @product.errors, status: :unprocessable_entity }
    #   end
    # end


      @product = Product.create(roomname: product_params[:roomname], image: product_params[:image], text: product_params[:text], user_id: current_user.id)

      # respond_to do |format|
      #   if @product.save
      #     format.html { redirect_to @product, notice: 'Post was successfully created.' }
      #     format.json { render :show, status: :created, location: @product }
      #   else
      #     format.html { render :new }
      #     format.json { render json: @product.errors, status: :unprocessable_entity }
      #   end
      # end
    end

    def destroy
      product = Product.find(params[:id])
      product.destroy if product.user_id == current_user.id

    end

    def edit
      @product = Product.find(params[:id])
    end

    def update
      product = Product.find(params[:id])
      if product.user_id == current_user.id
        product.update(product_params)
      end

      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to @product, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews.includes(:user)
    @review = Review.new
    end

    private
    # def product_params
    #   params.permit(:roomname, :image, :text)
    # end

    def product_params
      params.require(:product).permit(:roomname, :text, :image)
    end

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>@product = Product.new
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :roomname %><br>
    <%= f.text_field :roomname %>

  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<tr>
  <td><%= image_tag product.image,:size =>'320x480' %></td>
</tr>
<span class="name">
  <p>
    <span>作成者：</span><%= product.user.nickname %>
  </p>
  <p>
    <span>部屋の名前：</span><%= product.roomname %>
  </p>
</span>
<ul class="more_list">
  <li>
    <%= link_to '詳細', "/products/#{product.id}", method: :get %>
  </li>
</ul>

app/views/products/create.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/products">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/products/destroy.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @Product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id="main_cnt_wrapper">
<div id="yjContentsBody">
  <div class="yjContainer">
    <span class="yjGuid"><a id="yjContentsStart" name="yjContentsStart"></a><img alt="ここから本文です" height="1" src="http://i.yimg.jp/yui/jp/tmpl/1.1.0/audionav.gif" width="1"></span>

    <div id="yjMain">
      <h2 class="text-middle">
        <i class="icon-movie color-gray-light"></i>新着作品
      </h2>
      <article class="section">
        <div class="container">
          <ul class="thumbnails thumbnail--movies row grid4 js-lazy-load-images js-my-check-stats" id="list-module">
            <% @products.each do |product| %>
            <li class="col">
              <a href="/products/<%= product.id %>"><div class="thumbnail__figure" style="background-image:url(<%= product.image_url %>)"></div></a>
              <div class="thumbnail__caption">
                <h3 class="text-xsmall text-overflow" title="<%= product.roomname %>">
                  <%= product.roomname %>
                </h3>
                <p class="text-small">
                  <% if product.reviews.present? %>
                  <span class="rating-star">
                    <i class="star-actived rate-<%= product.review_average %>0"></i>
                  </span>
                  <% else %>
                  <span class="rating-star">
                    <i class="star-actived rate-0"></i>
                  </span>
                  <% end %>
                </p>
              </div>
            </li>
            <% end %>
          </ul>
        </div>
      </article>
    </div>
    <div id="yjSub">

app/views/products/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class ="contents row">
  <p><%= image_tag @product.image, :size =>'320x480'%></p>
<!-- <p id="notice"><%= notice %></p> -->
<p>
  <strong>部屋の名前:</strong><%= @product.roomname %>
</p>
<p>
  <a href="/users/<%= @product.user.id %>">
    <strong>作成者:</strong><%= @product.user.nickname %>
  </a>
</p>
<p>
  <strong>メッセージ:</strong><%= @product.text %>
</p>


<% if user_signed_in? && current_user.id == @product.user_id %>
  <div class="more">
  <ul class="more_list">
    <li>
      <%= link_to '編集', "/products/#{@product.id}/edit", method: :get %>
    </li>
    <li>
      <%= link_to '削除', "/products/#{@product.id}", method: :delete %>
    </li>
  </ul>
</div>
<% end %>
    <!-- ここからフォーム -->
    <% if current_user %>
      <%= form_for [@product, @review] do |f| %>
        <div style="margin: 8px 0">
          <%= f.label :rate, '評価', style: { 'margin-right' => 8 } %>
          <%= f.number_field :rate, placeholder: '評価', value: 1, max: 10, min: 1, html: { class: "search__query", style: 'text-align: right;' } %>
        </div>
        <div style="margin: 8px 0">
          <%= f.text_area :review, placeholder: 'レビューを書いてね！', style: 'width: 100%;height: 300px;' %>
        </div>

        <div class="row">
          <div class="col10 push1">
            <%= button_tag type: "submit", class: "btn btn--block" do %>
            投稿する<i class="icon-arrow-right"></i>
            <% end %>
          </div>
        </div>
      <% end %>

    <% end %>
    <div class="reviews">
      <h4>＜コメント一覧＞</h4>
      <% if @reviews %>
        <% @reviews.each do |review| %>
          <p>
            <strong><%= link_to review.user.nickname, "/users/#{review.user_id}" %>：</strong>
            <span class="rating-star"><i class="star-actived rate-<%= review.rate %>0"></i></span>
            <%= review.review %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
  <%= link_to 'Back', products_path %>
</div>

app/views/products/update.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>